### ISSUE TITLE
TODO: before launch

### ISSUE THREAD

**Issue by housseindjirdeh** [GoogleChromeLabs/perf-track#3]
- [X] Use latest results from HTTP Archive/CrUX
- [X] Include more Web Vital metrics and surface them better
  - [X] Largest Contenful Paint
  - [X] Cumulative Layout Shift
  - [X] First Input Delay
- [X] Clean things up
  - [X] Improve design/clean up styles
  - [X] Update README
  - [X] Make mobile responsive
- [X] Add analytics

---------

Nice to haves:

- [ ] Use BigQuery API to fetch data instead of local JSON files
- [ ] Add a few more technologies: 
  - [ ] Lit
  - [X] Ember
  - [X] Preact
  - [X] AMP
- [ ] Compare SSR versus CSR sites for any of the frameworks
  - (different toggles to switch between SSR/CSR)
- [ ] Include CMSs (Shopify, Magento, WordPress, etc...)
- [ ] Switch to a lighter charting lib
- [ ] Versioning support

**Comment by developit** [comment]
One suggestion - I wonder if it would be possible to add some generalized confounders that can be added to each framework view. Essentially the opposite of "React sites with Next.js" - "React sites without jQuery" or "React sites without Bootstrap".

**Comment by housseindjirdeh** [comment]
@developit Analyzing usage and performance without jQuery has been widely requested, so it's definitely useful.

Added an issue :) #9
